name: model-training

on: [push]

jobs:
  deploy-cloud-runner:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-cloud-runner

    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          key_value: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "Deploying..."
          MACHINE="CML-$(openssl rand -hex 4)"
          echo -n  "$key_value" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="key.json"
          docker-machine create --driver google --google-project $PROJECT_ID test
