name: model-training

on: [push]

jobs:
  deploy-cloud-runner:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3-cloud-runner

    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "Deploying..."
          # Add the Cloud SDK distribution URI as a package source
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

          # Import the Google Cloud Platform public key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

          # Update the package list and install the Cloud SDK
          sudo apt-get update && sudo apt-get install google-cloud-sdk

          MACHINE="cml-$(openssl rand -hex 4)"
          docker-machine create --driver google --google-project $PROJECT_ID $MACHINE
          echo ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} > key.json
          export GOOGLE_APPLICATAION_CREDENTIALS=key.json
          gcloud auth activate-service-account ${{ secrets.SERVICE_ACCOUNT }} --key-file key.json  --project $PROJECT_ID

          eval "$(docker-machine env --shell sh $MACHINE)"
          (
          docker-machine ssh $MACHINE "sudo mkdir -p /docker_machine && sudo chmod 777 /docker_machine" && \
          docker-machine scp -r -q ~/.docker/machine/ $MACHINE:/docker_machine && \
          docker run --name runner -d \
            -v /docker_machine/machine:/root/.docker/machine \
            -e RUNNER_IDLE_TIMEOUT=120 \
            -e DOCKER_MACHINE=${MACHINE} \
            -e RUNNER_LABELS=cml \
            -e repo_token=$repo_token \
            -e RUNNER_REPO=https://github.com/KUrushi/cml_base_case \
           dvcorg/cml-py3-cloud-runner && \
          sleep 20 && echo "Deployed $MACHINE"
          ) || (echo y | docker-machine rm $MACHINE && exit 1)

  train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted,cml]

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          cat metrics.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md